### PR TITLE
some ImagicalMine  stuff

### PR DESCRIPTION
**Pull request by ghost**
## Have you tested?
- [x] I have tested.
- [ ] I haven't tested.

### CODE REVIEW

**Comment by ondraczsk** [comment]
wait a minute im setting up travis ci

**Comment by ghost** [comment]
@ondraczsk give  me full perm i know travis good and circleci

**Comment by ondraczsk** [comment]
@caspervanneck full perm as owner?

**Comment by ghost** [comment]
no as writen things

**Pull request merged**
